### ISSUE TITLE
Configuring the sp360

### ISSUE THREAD

**Issue by niallomahony93** [uts-magic-lab/kodak_pixpro_sp360_ros#1]
The Readme includes instructions for setting the sp360 4k to webcam mode, however, there seems to be no such feature on the sp360 model. Has this code been tested with the sp360?

**Comment by awesomebytes** [comment]
No, I haven't tested it with any other camera than the one described in the readme

**Comment by niallomahony93** [comment]
In that case, please remove any indication that this will work with the sp360 2k model as only the pixpro sp360 4k has webcam functionality. It might someone else acquiring the sp360 in the hopes of using it with ROS as I did.

**Comment by awesomebytes** [comment]
The README clearly states "Kodak PIXPRO SP360 4K 360º" and I haven't seen anywhere else written it supports another camera. If you find somewhere delete it and do a PR and I'll merge it.

Sorry to hear you bought the camera with that intention.

**Comment by awesomebytes** [comment]
Given there is no more feedback and this repo never tried to announce it could use any other camera (and it's more of a README than a software package anyways) I'm closing this issue.
