### ISSUE TITLE
30% OF IMAGE REGION IS GETTING CROPPED.

### ISSUE THREAD

**Issue by karandeepdps** [uts-magic-lab/kodak_pixpro_sp360_ros#2]

**Comment by karandeepdps** [comment]
Did you find any other method which is more efficient as I don't want to lose information.

**Comment by awesomebytes** [comment]
Please don't use caps if not needed :) it's like shouting in the internet.

No, I don't know and other way. Maybe trying with gscam and playing with
the size parameters of the image may work. That's all I can think of.

**Comment by awesomebytes** [comment]
Also, I haven't found any % of the image lost. As you can see in the screenshot in the README.

Can you show what is happening to you?
